/*
	CADET - Center for Advances in Digital Entertainment Technologies
	Copyright 2011 Fachhochschule Salzburg GmbH
		http://www.cadet.at

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

#pragma once

#include "helpers/_2RealStdIncludes.h"
#include "helpers/_2RealVersion.h"
#include "helpers/_2RealPath.h"
#include "engine/_2RealDeclarations.h"

namespace _2Real
{

	class SharedLibrary;
	class SharedTypeMetainfo;
	class SharedServiceMetainfo;
	class TypeCollection;
	class MetainfoId;

	class SharedLibraryMetainfo
	{

	public:


		static std::shared_ptr< SharedLibraryMetainfo > make( std::shared_ptr< SharedLibrary >, Path const&, std::shared_ptr< TypeCollection > );

		SharedLibraryMetainfo() = delete;
		SharedLibraryMetainfo( SharedLibraryMetainfo const& other ) = delete;
		SharedLibraryMetainfo( SharedLibraryMetainfo && other ) = delete;
		SharedLibraryMetainfo& operator=( SharedLibraryMetainfo const& other ) = delete;
		SharedLibraryMetainfo& operator=( SharedLibraryMetainfo && other ) = delete;

		~SharedLibraryMetainfo() = default;

		std::string				getDescription() const;
		std::string				getAuthor() const;
		std::string				getContact() const;
		std::string				getCategory() const;
		Version					getVersion() const;

		void					setDescription( std::string const& );
		void					setAuthor( std::string const& );
		void					setContact( std::string const& );
		void					setCategory( std::string const& );
		void					setVersion( Version const& );

		std::vector< std::shared_ptr< const SharedServiceMetainfo > >	getServiceMetainfos() const;
		std::vector< std::shared_ptr< const SharedTypeMetainfo > >		getTypeMetainfos() const;

		std::shared_ptr< const SharedServiceMetainfo >					getServiceMetainfo( std::string const& ) const;
		std::shared_ptr< const SharedTypeMetainfo >						getTypeMetainfo( std::string const& ) const;

		void	exportType( const std::string, const std::vector< FieldDeclaration > );
		void	exportBlock( const std::string, const bool, const std::vector< InletDeclaration >, const std::vector< OutletDeclaration >, const std::vector< ParameterDeclaration > );

		std::shared_ptr< const MetainfoId > getId() const;

	private:

		SharedLibraryMetainfo( std::shared_ptr< const MetainfoId > id, std::shared_ptr< TypeCollection > );

		// metainfo id as generated by the framework
		std::shared_ptr< const MetainfoId >		mId;

		// basic info, bundle metainfo provides setters here
		std::string mCategory;
		std::string mDescription;
		std::string mAuthor;
		std::string mContact;
		Version		mVersion;

		typedef std::map< std::string, std::shared_ptr< SharedServiceMetainfo > >	ServiceMetainfos;
		typedef std::map< std::string, std::shared_ptr< SharedTypeMetainfo > >		TypeMetainfos;

		typedef std::vector< TypeDeclaration >	TypePreinfos;
		typedef std::vector< BlockDeclaration >	BlockPreinfos;

		TypePreinfos		mTypePreinfos;
		BlockPreinfos		mBlockPreinfos;

		std::weak_ptr< TypeCollection >		mTypeCollection;
		TypeMetainfos						mTypes;
		ServiceMetainfos					mBlocks;

	};

}